---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/actions"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
