project_name: testing-things

snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

signs:
  - signature: "${artifact}.sig"
    cmd: cosign
    args: ["sign-blob", "-output", "${artifact}.sig", "-key", "cosign.key", "${artifact}"]
    artifacts: binary
    stdin: "{{ .Env.COSIGN_PASSWORD }}"

archives:
  - format: binary
# release:
#   extra_files:
#     - glob: dist/*.sig
