project_name: testing-things

env:
  - API_ENDPOINT={{ if index .Env "API_ENDPOINT"}}{{ .Env.API_ENDPOINT }}{{ else }}test{{ end }}
  - COSIGN_EXPERIMENTAL=true
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: test_{{ .Os }}_{{ .Arch }}{{ with .Arm }}_{{ . }}{{ end }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"

signs:
  - id: binary
    artifacts: binary
    signature: "${artifact}.sig"
    certificate: "${artifact}.cert.pem"
    cmd: cosign
    args:
      - sign-blob
      - "--output-signature=${artifact}.sig"
      - "--output-certificate=${artifact}.cert.pem"
      - "${artifact}"
  - id: checksum
    artifacts: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.cert.pem"
    cmd: cosign
    args:
      - sign-blob
      - "--output-signature=${artifact}.sig"
      - "--output-certificate=${artifact}.cert.pem"
      - "${artifact}"

archives:
  - format: binary
