version: 2.1
executors:
  default:
    docker:
    - image: cimg/go:1.17.4
  release:
    docker:
    - image: cimg/go:1.17.4
    - image: gcr.io/projectsigstore/cosign:v1.4.1@sha256:502d5130431e45f28c51d2c24a05ef5ccd3fd916bcc91db0c8bee3a81e09a0bb
    - image: docker.io/anchore/syft:v0.34.0@sha256:ae6c51aae1de6e990e994b43943a7ce83823949dfe9e755cccd373e7deab3f8e

jobs:
  test-release:
    executor:
      name: release
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Release
        no_output_timeout: 30m
        command: |
          cosign version
          syft version

workflows:
  ci-build:
    jobs:
    - test-release
