version: 2.1
executors:
  default:
    docker:
    - image: cimg/go:1.17.4

orbs:
  cosign-orb: cpanato/cosign-orb@1.2.0

jobs:
  test-release:
    executor:
      name: default
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
    - checkout
    - setup_remote_docker
    - cosign-orb/install
    - run:
        name: Release
        no_output_timeout: 30m
        command: |
          cosign version

workflows:
  ci-build:
    jobs:
    - test-release:
        context: test-cosign
