version: 2.1

jobs:
  test-webapp:
    docker:
      - image: cimg/go:1.16.11
    steps:
      - setup_remote_docker
      - run:
          name: checkout
          command: git clone https://github.com/cpanato/falcosidekick.git
      - run:
          name: prepare qemu
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
          name: Release
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  ci-build:
    jobs:
    - test-webapp
