apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "https://github.com/cert-manager/cert-manager/releases/download/v1.11.1/cert-manager.yaml"

patchesJSON6902:
  # dogfood our chainguard images:
  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-controller
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cgr.dev/chainguard/cert-manager-controller:latest@sha256:4c72a082bc5e088ba1896c41954966389586de3ed5fae83e3cc825c1e4870c16

  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-cainjectors
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager-cainjector
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cgr.dev/chainguard/cert-manager-cainjector:latest@sha256:af2ab986f3d2011b1e15e626a0e69ca464348c46b191e8044ae1caad1cae8dbb

  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-webhook
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager-webhook
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cgr.dev/chainguard/cert-manager-webhook:latest@sha256:7e06fed7574797f69ff59d5004a0c9c6099e3d7f919bfd40ac174c108304b006

  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-acmesolver
  # When updating to a new certmanager release this please make sure that the args are still in that position
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: --acme-http01-solver-image=cgr.dev/chainguard/cert-manager-acmesolver:latest@sha256:e0b4cc524623ac7a1e0527035e91ed4dc3e66b7c3c9ceea7e0fa06e74138d3db
