apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "https://github.com/cert-manager/cert-manager/releases/download/v1.11.1/cert-manager.yaml"

patchesJSON6902:
  # dogfood our chainguard images:
  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-controller
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cgr.dev/chainguard/cert-manager-controller:1.11.1@sha256:819a8714fc52fe3ecf3d046ba142e02ce2a95d1431b7047b358d23df6759de6c

  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-cainjectors
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager-cainjector
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cgr.dev/chainguard/cert-manager-cainjector:1.11.1@sha256:9f90a2d54d32e16d827985ded5628692e1fae9861f5df2ccfab99d6a6c506d6d

  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-webhook
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager-webhook
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cgr.dev/chainguard/cert-manager-webhook:1.11.1@sha256:4b24584a2243a3a0f2eb40d042c4eca0d143c99465aa6a96bcd6cf3cb75ed6ad

  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-acmesolver
  # When updating to a new certmanager release this please make sure that the args are still in that position
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: --acme-http01-solver-image=cgr.dev/chainguard/cert-manager-acmesolver:1.11.1@sha256:059c0b906e1f0f031e8a4a55d43e193d6b1e75e99f8eb9ae406ecdea7c99ec42
