
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "https://github.com/cert-manager/cert-manager/releases/download/v1.11.1/cert-manager.yaml"


patchesJSON6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cgr.dev/chainguard/cert-manager-controller:1.11.1@sha256:5db8184cf49589979c786a20cb9f5b2ce4352dae9329be78acef78ecff7d2d42
