apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "https://github.com/cert-manager/cert-manager/releases/download/v1.11.1/cert-manager.yaml"

patchesJSON6902:
  # dogfood our chainguard images:
  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-controller
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cgr.dev/chainguard/cert-manager-controller:latest@sha256:b8e98bdec6d8a03c3eca66b27a28431e92c891601c0a62e52973c1eabae65432

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager-cainjector
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cgr.dev/chainguard/cert-manager-cainjector:latest@sha256:d5cf8e804a62a30d67fdee9b8f1494b4490bfe0b75c1c2dae4fd424ddb4fa40f

  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-webhook
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager-webhook
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cgr.dev/chainguard/cert-manager-webhook:latest@sha256:6084625362e2376649d3e8eb110975c0d3b2953974abac3222b209b07c954f1d

  # ref: https://github.com/chainguard-images/images/tree/main/images/cert-manager-acmesolver
  # When updating to a new certmanager release this please make sure that the args are still in that position
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: --acme-http01-solver-image=cgr.dev/chainguard/cert-manager-acmesolver:latest@sha256:74c136e0dc25412f5145d52f741fea2a00d4e988a865daf9ab40ef9b9e1878ce
