name: Docker Build
description: Builds linkerd's docker images

inputs:
  docker-registry:
    description: The docker registry used to tag the images
    required: false
    default: cr.l5d.io/linkerd
  docker-target:
    description: The OS-arch the docker build will be targeted to
    required: false
    default: linux-amd64
  docker-push:
    description: Whether to push the built images to the registry
    required: false
    default: ''
  docker-ghcr-username:
    description: GH username under which to push images
    required: false
  docker-ghcr-pat:
    description: GH PAT for docker-ghcr-username
    required: false
  component:
    description: Component to build
    required: true
  tag:
    description: Tag to use for the built image
    required: true

runs:
  using: composite
  steps:
    - name: Output Image Digest
      shell: bash
      id: image_digest
      run: |
        image_digest=blablalbalbal
        echo "${image_digest}"
        echo "DIGEST=${{ inputs.docker-registry }}/${{ inputs.component }}@${image_digest}" >> "$GITHUB_OUTPUT"

    # Delete older docker images to prevent cache bloat.
    - run: bin/docker-cache-prune
      shell: bash

outputs:
  digest:
    description: The image digest
    value: ${{ steps.image_digest.output.DIGEST }}
