name: Docker Build
description: Builds linkerd's docker images

inputs:
  docker-registry:
    description: The docker registry used to tag the images
    required: false
    default: cr.l5d.io/linkerd

runs:
  using: composite
  steps:
    - name: Output Image Digest
      shell: bash
      id: image_digest
      run: |
        image_digest=blablalbalbal
        echo "${image_digest}"
        echo "DIGEST=${{ inputs.docker-registry }}/${{ inputs.component }}@${image_digest}" >> "$GITHUB_OUTPUT"

outputs:
  digest:
    description: The image digest
    value: ${{ steps.image_digest.outputs.DIGEST }}
