name: 'Update the image digest'
description: 'Update the image digest when have a mutating tag'
branding:
  icon: box
  color: green

runs:
  using: "composite"
  steps:
  - uses: imjasonh/setup-crane@v0.1
  - shell: bash
    run: |
      while IFS= read -r -d '' file; do
          # single filename is in $file
          echo "$file"
          images=$(grep -i -E '[a-z0-9]+([._-][a-z0-9]+)*(/[a-z0-9]+([._-][a-z0-9]+)*)*@sha256:[a-z0-9]+' "$file" | cut -d @ -f1 | rev | cut -d ' ' -f1 | cut -d '"' -f1 | rev | sed -e "s/^docker:\/\///" | tr '\n' ',' || true)
          digests=$(grep -i -E '[a-z0-9]+([._-][a-z0-9]+)*(/[a-z0-9]+([._-][a-z0-9]+)*)*@sha256:[a-z0-9]+' "$file" | cut -d @ -f2 | cut -d ' ' -f1 | cut -d '"' -f1 | tr '\n' ',' || true)
          IFS=',' read -r -a images2 <<< "$images"
          IFS=',' read -r -a digests2 <<< "$digests"

          if [ -n "$images" ]; then
              for i in "${!images2[@]}"; do
                echo "Processing ${images2[i]} in file $file"
                updated_digest=$(crane digest "${images2[i]}")
                if [ "$updated_digest" != "${digests2[i]}" ] && [ -n "$updated_digest" ]; then
                  echo "Digest ${digests2[i]} for image ${images2[i]} is different, new digest is $updated_digest, updating..."
                  sed -i -e "s/${digests2[i]}/$updated_digest/g" "$file"
                  echo "done"
                fi
                echo "done2"
              done
              echo "done3"
          fi
          echo "done4"
      done < <(find "$(pwd)" -type f \( -name "*.yaml" -o -name "*.yml" -o -name "Dockerfile*" \) -print0)