name: 'Update the image digest'
description: 'Update the image digest when have a mutating tag'
branding:
  icon: box
  color: green

runs:
  using: "composite"
  steps:
  - uses: imjasonh/setup-crane@v0.1
  - shell: bash
    run: |
      files=$(find "$(pwd)" -type f -name "*.yaml" -follow -print)
      for file in $files
      do
          images=$(grep -E '[a-z0-9]+([._-][a-z0-9]+)*(/[a-z0-9]+([._-][a-z0-9]+)*)*@sha256:[a-z0-9]+' "$file" | cut -d @ -f1 | rev | cut -d ' ' -f1 | cut -d '"' -f1 | rev | sed -e "s/^docker:\/\///" | tr '\n' ',')
          digests=$(grep -E '[a-z0-9]+([._-][a-z0-9]+)*(/[a-z0-9]+([._-][a-z0-9]+)*)*@sha256:[a-z0-9]+' "$file" | cut -d @ -f2 | cut -d ' ' -f1 | cut -d '"' -f1 | tr '\n' ',')
          IFS=',' read -r -a images2 <<< "$images"
          IFS=',' read -r -a digests2 <<< "$digests"

          if [ -n "$images" ]; then
              for i in "${!images2[@]}"; do
                echo "Processing ${images2[i]} in file $file"
                updated_digest=$(crane digest "${images2[i]}")
                if [ "$updated_digest" != "${digests2[i]}" ] && [ -n "$updated_digest" ]; then
                  echo "Digest ${digests2[i]} for image ${images2[i]} is different, new digest is $updated_digest, updating..."
                  cat "$file"
                  sed -i '' -e "s/${digests2[i]}/$updated_digest/g" "$file"
                fi
              done
          fi
      done
  - shell: bash
    run: |
      git status
