issuer: https://token.actions.githubusercontent.com
subject: repo:cpanato/testing-ci-private:ref:refs/heads/main

claim_pattern:
  job_workflow_ref: cpanato/testing-ci-private/.github/workflows/test-push-image.yaml@refs/heads/main

permissions:
  contents: read
  packages: write
