# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:cpanato/testing-ci-providers:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: cpanato/testing-ci-providers/.github/workflows/release-tag.yaml@refs/heads/main

# the release workflow needs write permissions to create and push tags
permissions:
  contents: write
  workflows: write
