name: "~ Template Release"

on:
  workflow_call:
    inputs:
      checkout_ref:
        required: true
        type: string
        description: 'Commit ref (sha, branch, or tag) to run at.'

permissions:
  contents: read

jobs:
  drop:
    name: Release Drop
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: continue
        if: ${{ inputs.checkout_ref == '' }}
        run: |
          echo "will be a full release"
