name: Add all update PRs to Images project

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/add-to-project@main
        continue-on-error: true
        with:
          project-url: https://github.com/orgs/kingdom-tower/projects/1
          github-token: ${{ secrets.PROJECT_WRITE }}
          labeled: request-version-update

      - if: always()
        run: exit 0
