name: container

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test_cosign_action:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    name: Install Cosign and test presence in path
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - uses: chainguard-dev/actions/setup-registry@main
        with:
          port: 1234

      - shell: bash
        id: mkconfig
        run: |
          TMP="$GITHUB_WORKSPACE/config_file"

          cat > "${TMP}" <<EOF
          contents:
            repositories: ["https://packages.wolfi.dev/os"]
            keyring: ["https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"]
            packages:
            - kos

          archs:
          - x86_64
          EOF

          echo "CONFIG_FILE=${TMP}" >> $GITHUB_ENV

      - shell: bash
        run: |
          cat ${{ steps.mkconfig.outputs.config-file }}

      - uses: chainguard-images/actions/apko-publish@main
        with:
          config: ${{ steps.mkconfig.outputs.config-file }}
          tag: localhost:1234/apk-scan
