name: apk-publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apk-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - uses: chainguard-dev/actions/setup-registry@main
        with:
          port: 1234
      - shell: bash
        run: |
          cat apko.yaml

      - uses: chainguard-images/actions/apko-publish@main
        id: apko-publish
        with:
          config: apko.yaml
          tag: localhost:1234/apk-scan

      - run: echo ${{ steps.apko-publish.outputs.digest}}
