name: apk-publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apk-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: message
        run: |
          echo "# Deprecation Notice" >> $GITHUB_STEP_SUMMARY
          echo "This repository is deprecated. Please do not add new infrastructure or features." >> $GITHUB_STEP_SUMMARY
          echo "Only bug fixes will be accepted." >> $GITHUB_STEP_SUMMARY
          echo "For new infrastructure, please use the recommended repositories and workflows." >> $GITHUB_STEP_SUMMARY
          echo "If you need any help please reach out to the SRE / Platform Engineering teams." >> $GITHUB_STEP_SUMMARY

      - uses: chainguard-dev/actions/setup-registry@de56c2728beb0a0f371bff2ce2ee4b8afee4b5e8 # v1.5.1
        with:
          port: 1234
      - shell: bash
        run: |
          cat apko.yaml
