name: apk-publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apk-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: message
        run: |
          echo "### Hello world! :rocket:"
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

      - uses: chainguard-dev/actions/setup-registry@16e2fd6603a1c6a1fbc880fdbb922b2e8e2be3e7 # v1.4.3
        with:
          port: 1234
      - shell: bash
        run: |
          cat apko.yaml
