# Sample Project builder
name: Build-Go
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    name: Build Test Project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
      - run: |
          echo "********************"
          echo ${{ github.event.pull_request.base.sha }}
          echo ${{ github.sha }}
          echo ${{ github.sha || github.event.pull_request.base.sha }}
          echo ${{ github.event.pull_request.base.sha || github.sha }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true

      - uses: helm/kind-action@v1.4.0
#       - uses: chainguard-dev/actions/setup-kind@main
#         with:
#           k8s-version: v1.25.x
          
      - run: kubectl get nodes
      - run: kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml
      - run: kubectl get po -A
          
      # - uses: actions/checkout@v3
      - run: |
          make build
          ./hello
      # - name: Store Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: hello
      #     path: ./hello
