name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  upload:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    steps:
      - name: 'Comment on PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.createComment({
              owner: github.event.pull_request.repo.owner,
              repo: github.event.pull_request.repo,
              issue_number: github.event.pull_request.number,
              body: 'Everything is OK. Thank you for the PR!'
            });
