# Sample Project builder
name: Build-Go
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


jobs:
  clank:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cpanato/actions/clank@add-clank

  build:
    name: Build Test Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "********************"
          echo ${{ github.event.pull_request.base.sha }}
          echo ${{ github.sha }}
          echo ${{ github.sha || github.event.pull_request.base.sha }}
          echo ${{ github.event.pull_request.base.sha || github.sha }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          check-latest: true

      - run: |
          set -euxo pipefail
          # eval `go env`, compatible with Windows and Linux
          # cribbed from https://gist.github.com/Syeberman/39d81b1e17d091be5657ecd6fbff0753
          export PLATFORM=$(go env GOOS)/$(go env GOARCH)
          echo ${PLATFORM}
        shell: bash

  build-w:
    name: Build Test Project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          check-latest: true

      - run: |
          set -euxo pipefail
          # eval `go env`, compatible with Windows and Linux
          # cribbed from https://gist.github.com/Syeberman/39d81b1e17d091be5657ecd6fbff0753
          export PLATFORM=$(go env GOOS)/$(go env GOARCH)
          echo ${PLATFORM}


        shell: bash
