name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  upload:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    steps:
      - name: 'Comment on PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Everything is OK. Thank you for the PR!'
            });

  test_cosign_action:
    runs-on: ubuntu-latest

    permissions:
      actions: none

    name: Install Cosign and test presence in path
    steps:
      - name: Install Cosign
        uses: sigstore/sigstore-installer@initial
        with:
          cosign-version: 'v1.5.2'
      - name: Check install!
        run: cosign version
      - name: Check install!
        run: rekor-cli version
