name: check files1

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  presubmit-matrix:
    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p ${{ env.GITHUB_WORKSPACE }}/new-folder
    - run: touch ${{ env.GITHUB_WORKSPACE }}/new-folder/a.txt
    - run: ls -la && ls -la ${{ env.GITHUB_WORKSPACE }}/new-folder
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - run: ls -la && ls -la ${{ env.GITHUB_WORKSPACE }}/new-folder


    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        separator: ','

    - name: List all changed files
      run: |
        echo ${{ steps.changed-files.outputs.all_changed_files }}
