name: Changelog CI

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_VERSION }}

      - run: cat CHANGELOG.md

      - name: Check workspace
        id: create_pr
        shell: bash
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo ::set-output name=create_pr::true
          fi
      # # Configure signed commits
      # - uses: chainguard-dev/actions/setup-gitsign@main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27 # v4
        if: ${{ steps.create_pr.outputs.create_pr == 'true' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'doc: update changelog'
          title: 'doc: update changelog'
          body: update changelog
          labels: docs, automated pr
          branch: update-changelog
          base: main
          delete-branch: true
