name: Release Charts

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*'
    paths:
      - charts/**

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        id: release
        # uses: helm/chart-releaser-action@v1.5.0
        uses: odenio/chart-releaser-action@main
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - run: |
          echo ${{ steps.release.outputs.changed_charts }}
          echo ${{ steps.release.outputs.chart_version }}
