name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    container: ghcr.io/cpanato/chart-releaser:latest-amd64@sha256:ce2712f156eac5668b7129e2e97762aa6ddc6340ba8c0c56119002e5ad3ccd29

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Install Cosign
        uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2

      - name: Configure Git
        run: |
          ls -la
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 # v1.5.0
      #   with:
      #     charts_dir: charts
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: vector-im/chart-releaser-action@1389a6afc9af1b11ab9e79267f371d694e4995b2
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          skip_cr_install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish and Sign OCI Charts
        run: |
          for chart in `find .cr-release-packages -name '*.tgz' -print`; do
            helm push ${chart} oci://ghcr.io/${GITHUB_REPOSITORY} |& tee helm-push-output.log
            file_name=${chart##*/}
            chart_name=${file_name%-*}
            digest=$(awk -F "[, ]+" '/Digest/{print $NF}' < helm-push-output.log)
            cosign sign "ghcr.io/${GITHUB_REPOSITORY}/${chart_name}@${digest}"
          done
        env:
          COSIGN_YES: true
