name: Check External Dependencies

on:
  workflow_dispatch:
  schedule:
    # run every day at nigth
    - cron: '0 0/1 * * *'

permissions:
  contents: read
  issues: write

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: cpanato/setup-zeitgeist@6ac024d7412af63e758009740c188a9fd0033d9b # v0.0.1

      - run: |
          zeitgeist export --config external-dependencies.yaml --output-file out.yaml --output-format yaml
          if grep -q "\\[\\]" out.yaml; then
            exit 0;
          fi
          OUTDATED_DEPENDENCIES="$(cat out.yaml)"
          echo 'OUTDATED_DEPENDENCIES<<EOF' >> $GITHUB_ENV
          echo "$OUTDATED_DEPENDENCIES" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@b02a3c1d9d929a5839315bd255e40389f0dab627 # v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: New External Dependencies Images available
          body: |
            ## New External Dependencies Images available

            ```yaml
            ${{ env.OUTDATED_DEPENDENCIES }}
            ````
