name: Repository Dispatch
on:
  repository_dispatch:
    types: [create-check]
jobs:
  create-check:
    permissions:
      statuses: writes
    runs-on: ubuntu-latest
    steps:
      - uses: cpanato/commit-status-updater@add-sha
        with:
          name: " ${{ github.event.client_payload.check }}"
          status: "success"
          sha: ${{ github.event.client_payload.sha }}
          description: " ${{ github.event.client_payload.check }} skipped!"
