# Sample Project builder
name: testing-checkout
on:
  workflow_dispatch:


jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          path: private

      - run: ls -la

      - uses: actions/checkout@v4.1.0
        with:
          clean: false
          repository: 'cpanato/vault-installer'
          path: public

      - run: ls -la
