name: Repository Dispatch
on:
  repository_dispatch:
    types: [create-check]
jobs:
  create-check:
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@v1.6.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.client_payload.check }}
          status: completed
          conclusion: neutral
