name: Check External Dependencies

on:
  workflow_dispatch:
  schedule:
    # run every day at night
    - cron: '0 0 * * *'

permissions:
  contents: read
  issues: write

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: cpanato/setup-zeitgeist@3e861b7af3b3b4096b0b4837b612bf0665bdb308 # v0.0.2

      - run: |
          zeitgeist export --config external-dependencies.yaml --output-file out.yaml --output-format yaml
          if grep -q "\\[\\]" out.yaml; then
            exit 0;
          fi
          OUTDATED_DEPENDENCIES="$(cat out.yaml)"
          echo 'OUTDATED_DEPENDENCIES<<EOF' >> $GITHUB_ENV
          echo "$OUTDATED_DEPENDENCIES" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Find issues
        uses: actions-cool/issues-helper@65840f57fe2b3b9a796776577b6b19d2a16adc72 # v3.4.0
        id: find-issue
        with:
          actions: 'find-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-state: 'open'
          title-includes: "New External Dependencies Images available"

      - name: Create an issue
        if: fromJSON(steps.find-issue.outputs.issues)[0] == null
        uses: actions-ecosystem/action-create-issue@b02a3c1d9d929a5839315bd255e40389f0dab627 # v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: New External Dependencies Images available
          body: |
            ## New External Dependencies Images available

            ```yaml
            ${{ env.OUTDATED_DEPENDENCIES }}
            ````
