name: cherry-pick
on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        type: string
        default: ""
        required: true
      to_branch:
        type: string
        default: ""
        required: true
jobs:
  cherry-pick:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.1.7
      - uses: cpanato/cherry-pick-action@main
        with:
          pull_number: ${{ inputs.pull_request_number }}
          to_branch: ${{ inputs.to_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
