name: cherry-pick
on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        type: string
        default: ""
        required: true
      to_branch:
        type: string
        default: ""
        required: true
jobs:
  cherry-pick:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: cpanato/cherry-pick-action@main
        with:
          pull_number: ${{ inputs.pull_request_number }}
          to_branch: ${{ inputs.to_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
