name: cleanup caches by a branch
on:
  pull_request_target:
    types:
      - closed
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}

          if [[ "${{ github.event.pull_request }}" == "" ]]; then
            BRANCH="main"
            echo "Fetching list of cache key - $REPO - $BRANCH"
            # keep the last cache because that one is the current
            cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH --sort last-used --order asc | cut -f 1 | head -n -1)
          else
            BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"
            echo "Fetching list of cache key - $REPO/$BRANCH"
            cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )
          fi

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
            gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
