name: cosign with key
on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install cosign
        uses: sigstore/cosign-installer@v2.4.0

      - name: Install crane
        uses: imjasonh/setup-crane@v0.1

      - name: Build and sign a container image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo '${{ secrets.COSIGN_PRIVATE_KEY }}' > cosign.key
          cosign sign --key cosign.key ghcr.io/cpanato/testing-ci-providers/test:latest
