name: test output
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      packages: write
      contents: read
    env:
      COSIGN_EXPERIMENTAL: "true"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'

      - name: Install cosign
        if: ${{ github.event_name != 'pull_request' }}
        uses: sigstore/cosign-installer@v2.3.0

      - name: Install crane
        if: ${{ github.event_name != 'pull_request' }}
        uses: imjasonh/setup-crane@v0.1

      - name: Build and sign a container image
        env:
          COSIGN_EXPERIMENTAL: true
        run: |
          cosign sign ghcr.io/cpanato/testing-ci-providers/test:latest
      - name: Login to registry
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | docker login -u "${{ secrets.QUAY_USERNAME }}" --password-stdin quay.io
      - name: push to quay
        env:
          COSIGN_EXPERIMENTAL: true
        run: |
          cosign copy ghcr.io/cpanato/testing-ci-providers/test:latest quay.io/cpanato/testing-copy:latest
