name: test output
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      packages: write
      contents: read
    env:
      COSIGN_EXPERIMENTAL: "true"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'

      - name: Build and sign a container image
        run: |
          set -e
          go install github.com/sigstore/cosign/cmd/cosign@latest
          cosign sign-blob --output-certificate key.pem --output-signature README.md.sig README.md

          if [ -s key.pem ]
          then
            exit 0
          else
            echo "file does not exist, or is empty"
            exit 1
          fi
