name: Cut release

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: '1.23'
          check-latest: true

      - uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0

      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "curr_tag=$(git describe --abbrev=0)" >> $GITHUB_OUTPUT

      - uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          args: release --clean --parallelism 1 --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          CUSTOM_TAG: ${{ steps.vars.outputs.curr_tag }}-${{ steps.vars.outputs.sha_short }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          repository: cpanato/testing-ci-private
          tag_name: ${{ steps.vars.outputs.curr_tag }}-${{ steps.vars.outputs.sha_short }}
          files: |
            dist/test_*
            dist/*_checksums.txt
          token: ${{ secrets.GH_PAT }}
