name: Cut release

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: '1.23'
          check-latest: true

      - uses: sigstore/cosign-installer@c56c2d3e59e4281cc41dea2217323ba5694b171e # v3.8.0

      - name: Set outputs
        id: vars
        shell: bash
        run: |
          BASE_VERSION="0.0"
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          DAY=$(date +%d)
          HOUR=$(date +%H)
          MINUTE=$(date +%M)
          SECOND=$(date +%S)
          PATCH_VERSION="${YEAR}${MONTH}${DAY}${HOUR}${MINUTE}${SECOND}"
          echo "NEW_VERSION=${BASE_VERSION}.${PATCH_VERSION}" >> $GITHUB_OUTPUT

      - uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          args: release --snapshot --clean --parallelism 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ steps.vars.outputs.NEW_VERSION }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          repository: cpanato/testing-ci-private
          tag_name: ${{ steps.vars.outputs.NEW_VERSION }}-SNAPSHOT
          files: |
            dist/test_*
            dist/*_checksums.txt
          token: ${{ secrets.GH_PAT }}

      - name: Check out code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
        with:
          fetch-depth: 0
          repository: cpanato/testing-ci-private
          path: testing-ci-private
          token: ${{ secrets.GH_PAT }}

      - name: push update homebrew formula
        working-directory: testing-ci-private
        run: |
          git config --global user.name "cpanato"
          git config --global user.email "cpanato@users.noreply.github.com"

          ls -la ../
          mkdir -p Formula
          cp ../dist/homebrew/Formula/test.rb Formula/test.rb

          git add Formula/test.rb

          git commit -a -m "update test ${{ env.CUSTOM_TAG }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          CUSTOM_TAG: ${{ steps.vars.outputs.NEW_VERSION }}-SNAPSHOT
