name: Image digest update

on:
  workflow_dispatch:

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write
      actions: write

    steps:
      - run: jq --version
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: cpanato/digestabot@90ea1c8337f2a4287fdc69e1e908727eb9d3b2ac # multi-items
        id: digest-bot
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
          committer: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"

      - run: |
          echo "********"
          echo ${{ steps.digest-bot.outputs.pull_request_number }}
          echo "********"
