name: Image digest update

on:
  workflow_dispatch:

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write
      actions: write

    steps:
      - run: jq --version
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: chainguard-dev/digestabot@02ea60d2aeb26664ace4a9cc2ecdbea96888aaa4 # v1.2.0
        id: digest-bot
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
          committer: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"

      - run: |
          echo "********"
          echo ${{ steps.digest-bot.outputs.pull_request_number }}
          echo "********"
