name: Image digest update

on:
  workflow_dispatch:

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: chainguard-dev/actions/digesta-bot@main
        id: digest-bot
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: ${{ steps.digest-bot.outputs.pull_request_number != '' }}
        run: gh pr merge --auto --squash "https://github.com/chainguard-dev/mono/pull/${{ steps.digest-bot.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
