on:
  workflow_run:
    workflows:
      - Label-Checker
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pr_num.txt

      - run: cat pr_num.txt