on:
  workflow_run:
    workflows:
      - Label-Checker
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
  on-skipp:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'neutral' }}
    steps:
      - run: echo 'The triggering workflow neutral'
