name: GeneralTesting
on:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2

      - name: Drop bnd
        uses: cpanato/carabiner-dev-actions/drop@update-drop
        with:
          insecure: true
          binary: carabiner-dev/bnd
          install-dir: '$HOME/.carabiner'
