name: GeneralTesting
on:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2

      - name: Home
        run: |
          echo "HOME: $HOME"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_ENV: $GITHUB_ENV"
          echo "GITHUB_PATH: $GITHUB_PATH"

      - name: Drop bnd
        uses: carabiner-dev/actions/drop@main
        with:
          insecure: true
          binary: carabiner-dev/bnd
          directory: '$GITHUB_WORKSPACE/.carabiner'
