name: go action

on:
  pull_request_target:

jobs:
  preview:
    name: Preview Pulimi changes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: cpanato/testing-go-actions@main
      with:
        work_dir: github-sync
        stack_name: cpanato/dev
        pulumi_access_token: ${{ secrets.PULUMI_TOKEN }}
