name: test
on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Create k8s kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          wait: 300s
          cluster_name: kind
      - name: deploy
        run: |
          kubectl get po -A
          kubectl create ns dev
          kubectl create deployment --image nginx test -n dev
          kubectl wait --for=condition=Available --timeout=5m -n dev deployment/test

          kubectl get po -A
      - name: Collect logs
        if: always()
        run: |
          mkdir -p /tmp/logs
          kind export logs /tmp/logs
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: /tmp/logs    