name: test
on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Create k8s kind Cluster
        uses: cpanato/kind-action@update
        with:
          wait: 300s
          cluster_name: kind
      - name: Collect logs
        if: always()
        run: |
          mkdir -p /tmp/logs
          kind export logs /tmp/logs
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: /tmp/logs    