name: Label-Checker
on:
  pull_request:
    types:
      - labeled

jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'E2E')
    steps:
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt
      - name: Upload the PR number
        uses: actions/upload-artifact@v3
        with:
          name: pr_num
          path: ./pr_num.txt
