name: Label-Checker
on:
  pull_request:
    types:
      - labeled

jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'E2E')
    steps:
      - run: |
          echo "will trigger the workflow run to run e2e"
