name: build
on: 
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          cat m.json
          echo "matrix=$(cat m.json)" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    if: ${{ contains('{\"include\":null}', needs.job1.outputs.matrix) }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: echo ${{ fromJSON(needs.job1.outputs.matrix) }}

  job3:
    needs: job1
    if: ${{ contains('{\"include\":null}', fromJSON(needs.job1.outputs.matrix)) }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: echo ${{ fromJSON(needs.job1.outputs.matrix) }}