name: Test-matrix

on:
  pull_request:

jobs:
  gen-matrix:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ok"

  job-matrix:
    if: github.repository == 'to-skipp'
    needs:
      - gen-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        test-job:
          - bla
          - xoxo

    steps:
      - run: echo ${{ matrix.test-job }}
      - run: exit 0

  fan-in:
    needs:
      - job-matrix
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - run: echo ${{ env.WORKFLOW_CONCLUSION }}
