name: Test-matrix

on:
  pull_request:

jobs:
  gen-matrix:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ok"

  job-matrix:
    # if: github.repository == 'to-skipp'
    needs:
      - gen-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-job:
          - bla
          - xoxo

    steps:
      - run: echo ${{ matrix.test-job }}
      - run: exit 1

  fan-in:
    needs:
      - job-matrix
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
