name: Test-matrix

on:
  pull_request:

jobs:
  gen-matrix:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ok"

  job-matrix:
    # if: github.repository == 'to-skipp'
    needs:
      - gen-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        test-job:
          - bla
          - xoxo

    steps:
      - run: echo ${{ matrix.test-job }}
      - run: exit 0
        if: ${{ matrix.test-job == 'xoxo' }}
      - run: exit 1
        if: ${{ matrix.test-job == 'bla' }}

  fan-in:
    needs:
      - job-matrix
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3

      - if: ${{ env.WORKFLOW_CONCLUSION == 'success' }}
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 0

      - if: ${{ env.WORKFLOW_CONCLUSION == 'failure' }}
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 1
