name: Milestone

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: v1.2.0
            })
