name: Pull Request Milestone

on:
  pull_request:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.update({
              issue_number: context.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: "v1.2.0"
            })
