name: notify-mm-blog
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          set -x

          echo $github

          
          echo "{\"username\":\"GitHub Action Notify\",\"icon_url\":\"https://www.mattermost.org/wp-content/uploads/2016/04/icon.png\",\"attachments\":[{\"author_name\":\"test\",\"author_link\":\"cdcdcd",\"fallback\":\"test\",\"color\":\"good\",\"title\":\""xoxoxox"\",\"text\":\"blablabalbala"}]}"
