name: notify-mm-blog
on:
  push:
    paths:
      - 'site/content/blog/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          git ls-files --others --exclude-standard
          echo "{\"text\":\"New Blog Post\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
