name: notify-mm-blog
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          set -x

          TITLE=$(echo $GITHUB_CONTEXT | jq -r '.event.release.name')
          BODY=$(echo $GITHUB_CONTEXT | jq -r '.event.release.body')
          echo "{\"username\":\"Cloud Bot Notify\",\"icon_url\":\"https://www.mattermost.org/wp-content/uploads/2016/04/icon.png\",\"attachments\":[{\"fallback\":\"$BODY\",\"color\":\"good\",\"title\":\""$TITLE"\",\"text\":\"$BODY\"}]}" > mattermost.json

      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
