name: github pages

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Remove closed PR dirs from the generated site
        run: |
          echo ${{ github.event.number }}
