# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: "AWS Pre-submit check2"

on:
  pull_request_target:
    branches:
      - "main"

permissions: {}

jobs:
  aws2:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: './.github/actions/test-comp'
        with:
          cloud_provider: 'another-test'
          arch: '${{ matrix.arch }}'

      - run: |
          cat test-another-test-${{ matrix.arch }}.txt
