name: Publish
on:
  workflow_dispatch:
    inputs:
      ci:
        description: "Build and Test"
        required: false
        default: "testing-run.yml"
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Check CI status
        run: |
          output=$(curl -sSL -X GET -G -H "Accept: application/vnd.github.v3+json" -d "branch=${{ env.GITHUB_REF_SLUG }}" -d "event=push" https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.event.inputs.ci }}/runs | jq -r '.workflow_runs[0] | "\(.conclusion)"')
          echo "::set-output name=status::$output"
        id: check

      - name: Abort if CI not successful
        if: steps.check.outputs.status != 'success'
        run: |
          echo ${{ steps.check.outputs.status }}
          exit 1

      - name: output
        run: echo "success"
