name: release-notes

on:
  push:
    tags:
      - 'v*'

jobs:
  release-notes:

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get previous tag
        run: echo "PREVIOUS_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)" >> $GITHUB_ENV

      - name: Get current tag
        run: echo "CURRENT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: donmainb
        run: echo "DOMAIN=test.dev" >> $GITHUB_ENV

      - name: Get commit from tag
        run: echo "GIT_COMMIT=$(git rev-list -n1 "${{ env.CURRENT_TAG }}")" >> "$GITHUB_ENV"

      - run: echo $GIT_COMMIT

      - run: mkdir -p ./drop

      - name: "Download artifact"
        working-directory: "./drop/"
        run: |
          REPO="test/mono"
          WF_NAME="Provision Prod Infrastructure (enforce.dev)"
          ARTIFACT_NAME="drop-${{ env.DOMAIN }}-${{ env.GIT_COMMIT }}"
          RUN_ID=$(gh run --repo "${REPO}" list --workflow "${WF_NAME}" --json databaseId --jq '.[0].databaseId')
          gh run --repo ${REPO} download ${RUN_ID} -n ${ARTIFACT_NAME}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: cpanato/actions/release-notes@fix-relnotes
      #   with:
      #     branch_name: 'main'
      #     start_rev: ${{ env.PREVIOUS_TAG }}
      #     end_rev: ${{ env.CURRENT_TAG }}
      #     changelog_filename:  'CHANGELOG.md'
      #     token: ${{ secrets.GITHUB_TOKEN }}
