name: release-notes

on:
  push:
    tags:
      - 'v*'

jobs:
  release-notes:

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Get previous tag
        run: echo "PREVIOUS_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)" >> $GITHUB_ENV

      - name: Get current tag
        run: echo "CURRENT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout main branch
        run: git checkout main && git pull origin main

      - uses: chainguard-dev/actions/release-notes@main
        with:
          branch_name: 'main'
          start_rev: ${{ env.PREVIOUS_TAG }}
          end_rev: ${{ env.CURRENT_TAG }}
          changelog_filename:  'CHANGELOG.md'
          token: ${{ secrets.GITHUB_TOKEN }}
