name: release-notes

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-go:

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: sigstore/cosign-installer@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: Release chainctl with goreleaser
        uses: goreleaser/goreleaser-action@v3
        env:
          API_ENDPOINT: "https://api.${{ inputs.domain }}"
          CONSOLE_ENDPOINT: "https://console-ui.${{ inputs.domain }}"
          ISSUER_ENDPOINT: "https://issuer.${{ inputs.domain }}"
          CANARY_ENDPOINT: "https://canary.${{ inputs.domain }}"
          RELEASE_BUCKET: "${{ inputs.release_bucket }}"
        with:
          version: latest
          args: release --rm-dist
