name: release-tag

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "dry-run mode: if true, no git tags will be pushed."
        type: boolean
        default: false

permissions: {}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # to sign the release

    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: release

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          fetch-depth: 0

      - name: Check if any changes since last tag
        id: check
        run: |
          git fetch --tags
          if [ -z "$(git tag --points-at HEAD)" ]; then
            echo "Nothing points at HEAD, bump a new tag"
            echo "bump=yes" >> $GITHUB_OUTPUT
          else
            echo "A tag already points to head, don't bump"
            echo "bump=no" >> $GITHUB_OUTPUT
          fi

      - name: Bump and push Git tag
        uses: chainguard-dev/actions/git-tag@7d40b853210d271a28ac2822827f965f6f1e78fa # v1.0.9
        if: steps.check.outputs.bump == 'yes'
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          git_tag_prefix: "v"
          bump_level: patch
          dry_run: ${{ inputs.dry_run }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        if: steps.check.outputs.bump == 'yes'
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
