# .github/workflows/renovate.yaml
name: Renovate
on:
  schedule:
    - cron: "0 */4 * * *"   # every 4 hours
  workflow_dispatch:

permissions: {}

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write       # for octo-sts
    steps:
      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: renovate

      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.1.7
        with:
          token: ${{ steps.octo-sts.outputs.token }}

      - uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          configurationFile: .github/renovate.json
        env:
          LOG_LEVEL: debug
