name: Sync Org Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-labels.yaml
      - labels.json
      - repos.yaml
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.PAT_GITHUB}}
          script: |
            const repos = require(`${process.env.GITHUB_WORKSPACE}/repos.yaml`);
            console.log(repos);
