name: Terraform Checks

on:
  pull_request:
    paths:
    - 'terraform/**'
  push:
    branches:
      - main
    paths:
    - 'terraform/**'

jobs:
  terraform-fmt:
    name: 'Terraform fmt'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: 'Terraform Output'
        id: terraform
        uses: hashicorp/terraform-github-actions@b2ca17c0c25198c67c668c37edcbc45ca086a91e # v0.8.0
        with:
          # TODO: extract terraform from the tf file when we have pinned
          tf_actions_version: 1.1.6
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: './terraform/'

  terraform-tfsec:
    name: 'Terraform tfsec'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@868eade2142739cee2153c9ceff9eba4beded067 # v0.0.6
        with:
          sarif_file: tfsec.sarif
          working_directory: './terraform/'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
