name: Test

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  push:
    branches: [ 'main', 'release-*' ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@v3

    # https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
    - uses: actions/cache@v3
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go 1.17.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
        check-latest: true

    - name: Setup Cluster
      uses: chainguard-dev/actions/setup-kind@main
      id: kind
      with:
        k8s-version: v1.22.x
        registry-authority: registry.local:5000

    - run: |
        go test -race $(go list ./...)

    - name: Collect diagnostics and upload
      if: ${{ always() }}
      uses: cpanato/actions/kind-diag@fix-grafana
      with:
        start-time: ${{ steps.kind.outputs.kind-start-time }}
        grafana-dashboards: "gulfstream/gulfstream,knativereconciler/knative-reconciler"
