name: test123

on:
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Wolfictl Update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

    - uses: wolfi-dev/actions/install-wolfictl@install-wolfictl

    - run: wolfictl version
