name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases

    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.1.7
      - name: Publish Release
        # uses: kubernetes-sigs/release-actions/publish-release@main
        uses: cpanato/release-actions/publish-release@GH-107
        with:
            assets: "./labels.json"
            sbom: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
