name: "Build"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: 'release'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_TIMESTAMP: $(date --utc "+%Y%m%d-%H%M")

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: './.github/actions/test-comp'
        with:
          cloud_provider: 'testing'
          arch: '${{ matrix.arch }}'

      - name: Extract terraform version to use
        working-directory: './iac/github'
        run: echo "TERRAFORM_VERSION=$(grep -v "^\s*$"  "$GITHUB_WORKSPACE/.terraform-version")" >> "$GITHUB_ENV"

      - run: |
          echo "TERRAFORM_VERSION: ${{ env.TERRAFORM_VERSION }}"


      - run: |
          cat test-testing-${{ matrix.arch }}.txt
