name: Test

on:
  pull_request:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:

  build:
    name: Build Drop
    runs-on: ubuntu-latest

    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@v3

    - run: sleep 100

    - name: get epository name
      run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Set up Go 1.17.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
        check-latest: true

    - run: |
        go test -race $(go list ./...)
