name: test123

on:
  workflow_dispatch:


permissions:
  contents: read
  id-token: write
  pull-requests: write


jobs:
  update:
    name: Wolfictl Update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

    - uses: wolfi-dev/actions/wolfictl-update-gh@update-actions
      with:
        repository: ${{github.repository}}
        token: ${{ secrets.GITHUB_TOKEN }}
        git_author_name: ${{ env.GIT_AUTHOR_NAME }}
        git_author_email: ${{ env.GIT_AUTHOR_EMAIL }}
