name: "Build"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: 'release'
  cancel-in-progress: false

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      BUILD_TIMESTAMP: ${{ steps.timestamp.outputs.BUILD_TIMESTAMP }}
    steps:
      - id: timestamp
        run: |
          echo BUILD_TIMESTAMP=$(date --utc "+%Y%m%d-%H%M") >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: init
    env:
      BUILD_TIMESTAMP: ${{ needs.init.outputs.BUILD_TIMESTAMP }}

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

    steps:
      - uses: cpanato/testing-ci-providers/.github/workflows/.presubmit.yaml@main
        with:
          checkout_ref: ${{ github.ref }}
          cloud_provider: "aws"
          arch: ${{ matrix.arch }}

      - run: cat test-aws-${{ matrix.arch }}.txt
