name: Test Octo STS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for octo sts and signing
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
      id: octo-sts
      with:
        scope: ${{ github.repository }}
        identity: push

    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: octo-sts[bot]
        password: ${{ steps.octo-sts.outputs.token }}

    - run: |
        docker pull busybox:latest
        docker tag busybox:latest ghcr.io/cpanato/testing-ci-providers:latest
        docker push ghcr.io/cpanato/testing-ci-providers:latest
