name: Test Run

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          echo Sleeping...
          sleep $[ (50 + $RANDOM % 10 )  + 10 ]s
          echo DONE
  test123:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          echo Sleeping...
          timeout 300
          echo DONE
