name: Test Octo STS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for octo sts and signing
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
      id: octo-sts
      with:
        scope: ${{ github.repository }}
        identity: push

    - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: ghcr.io
        username: octo-sts[bot]
        password: ${{ steps.octo-sts.outputs.token }}

    - run: |
        docker pull busybox:latest
        docker tag busybox:latest ghcr.io/cpanato/testing-ci-providers:latest
        docker push ghcr.io/cpanato/testing-ci-providers:latest
