# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Verify AWS

on:
  pull_request_target:
    branches:
      - "main"

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      changed_paths: ${{ steps.filter.outputs.changes }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    permissions:
      contents: read # read repo
      pull-requests: read # read pull request contents

    steps:
      - uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            aws-marketplace:
              - 'test-folder/**'
            imgtest-infra:
              - 'iac/github/**'
          list-files: json

      - id: set-matrix
        run: |
          # Create a JSON object with information about each environment
          cat > aws-environments.json << EOF
          {
            "aws-marketplace": {
              "path": "test-folder",
              "region": "us-east-1",
              "account_id": "4444",
              "role_name": "44444-github-presub444mit-role"
            },
            "imgtest-infra": {
              "path": "charts",
              "region": "us-west-2",
              "account_id": "44444",
              "role_name": "4444-github-presubmit-role"
            }
          }
          EOF

          cat aws-environments.json

          # Get the list of environments with changes
          CHANGED_ENVS=$(echo '${{ steps.filter.outputs.changes }}' | jq .)

          # Generate matrix from changed environments
          MATRIX=$(jq -c --argjson names "$CHANGED_ENVS" '.| to_entries | map(select(.key as $k | $names | index($k) != null)) | map(.value + {"name": .key})' aws-environments.json)

          echo "matrix=${MATRIX}" >> "$GITHUB_OUTPUT"
          echo "Changed environments matrix: ${MATRIX}"

  verify-aws:
    needs: changes
    if: ${{ needs.changes.outputs.matrix != '[]' && needs.changes.outputs.matrix != '' }}

    strategy:
      matrix:
        aws-config: ${{ fromJSON(needs.changes.outputs.matrix) }}
      fail-fast: false

    permissions:
      contents: read # checkout PR
      id-token: write # federate
      pull-requests: write # write plan comment

    uses: ./.github/workflows/.presubmit.yaml
    with:
      cg_identity: ${{ matrix.aws-config.role_name }}
      path: ${{ matrix.aws-config.path }}
      checkout_ref: ${{ github.event.pull_request.head.sha || github.sha }}
      cloud_provider: 'GCP'
      push_vms: false

