name: Test

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '(v)?[0-9]+(\.[0-9]+)*(-.*)*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      release-workflow-run: ${GITHUB_RUN_ID}

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@v3

      # - uses: ./.github/actions/docker-build
      #   id: build
      #   with:
      #     docker-registry: xoxox/xoxo1

      # - run: echo ${{ steps.build.outputs.digest }}

      - name: get epository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      # - uses: actions/setup-go@v3
      #   with:
      #     go-version: 1.20.x
      #     check-latest: true
      #     cache: true

      - run: echo ${GITHUB_RUN_ID}


      # - run: |
      #     go test -race $(go list ./...)

  attest:
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - run: echo ${{ needs.test.outputs.release-workflow-run }}
      - run: echo ${GITHUB_RUN_ID}
