name: "Commit message validation"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

# permissions:
#   pull-requests: write

jobs:
  conventional:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # check for the most recent release: https://github.com/CondeNast/conventional-pull-request-action/releases
      # replace vX.X.X below with the most recently released version
      - uses: CondeNast/conventional-pull-request-action@v0.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
