name: Test Run

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          echo Sleeping...
          sleep $[ (10 + $RANDOM % 10 )  + 10 ]s
          echo DONE
