# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Verify AWS

on:
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      skip: ${{ steps.filter.outputs.changes }}


    permissions:
      contents: read # read repo
      pull-requests: read # read pull request contents

    steps:
      - uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            aws-marketplace:
              - 'test-folder/**'
            imgtest-infra:
              - 'iac/github/**'

  verify-aws:
    needs: changes
    if: ${{ needs.changes.outputs.skip == 'true' }}

    strategy:
      matrix:
        aws-config: ${{ fromJSON(needs.changes.outputs.matrix) }}
      fail-fast: false

    permissions:
      contents: read # checkout PR
      id-token: write # federate
      pull-requests: write # write plan comment
    runs-on: ubuntu-latest

    steps:
      - run: echo "No relevant changes, skipping AWS verification"

  presubmit-check:
    permissions:
      actions: read
    needs:
      - changes
      - verify-aws
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: technote-space/workflow-conclusion-action@45ce8e0eb155657ab8ccf346ade734257fd196a5 # v3.0.3

      - if: ${{ env.WORKFLOW_CONCLUSION == 'success' && needs.changes.outputs.skip == 'false' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 0

      - if: ${{ env.WORKFLOW_CONCLUSION == 'failure' && needs.changes.outputs.skip == 'false' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 1

      # exit 0 if no go file changed.
      - if: needs.changes.outputs.skip == 'true'
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 0
