name: "Build"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: 'release'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_TIMESTAMP: $(date --utc "+%Y%m%d-%H%M")

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

    steps:
      - uses: actions/checkout@v4

      - uses: './.github/actions/test-comp'
        with:
          cloud_provider: 'testing'
          arch: '${{ matrix.arch }}'

      - run: |
          cat test-testing-${{ matrix.arch }}.txt
