name: Test image digest update

on:
  workflow_dispatch:


defaults:
  run:
    shell: bash
    working-directory: ./

concurrency:
  group: test-github-action${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-image-update:
    name: Test image digest update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
    - name: Test running the action
      uses: ./actions/
    - name: check
      run: git --no-pager diff
