name: Test

on:
  pull_request:
  push:
    branches: [ 'main' ]
  schedule:
    - cron:  '0/15 * * * *'
jobs:

  test:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@v3

    - run: echo ${{ github.event.repository.name }}

    - run: echo ${{ github.env }}
    - run: echo ${{ env.REPO_NAME }}
    - name: Generate README
      uses: distroless/readme-generator@main
      with:
        repo: https://github.com/${{ github.repository }}
        name: ${{ env.REPO_NAME }}
        location: cgr.dev/chainguard/${{ env.REPO_NAME }}
        description: "WORK IN PROGRESS"
        exclude-tags: 1-r1
        push-to-repo: true

    # https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
    - uses: actions/cache@v3
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go 1.17.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
        check-latest: true

    - run: |
        go test -race $(go list ./...)

    - uses: nick-fields/retry@v2
      with:
        timeout_seconds: 15
        max_attempts: 3
        retry_on: error
        command: exit 1
