name: Test

on:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@v3

      - run: sudo apt-get update

      - name: get epository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          check-latest: true
          cache: true

      - run: |
          go test -race $(go list ./...)
