name: Dependabot Pull Request

on:
  pull_request_target:
    branches:
      - 'main'

permissions: {}

jobs:
  dependabot-check:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      dependabot-package-ecosystem: ${{ steps.dependabot-metadata.outputs.package-ecosystem }}

    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'cpanato/testing-ci-providers'
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v2.3.0


  go-mod-tidy:
    runs-on: ubuntu-latest

    needs: dependabot-check

    if: ${{ needs.dependabot-check.outputs.dependabot-package-ecosystem == 'go_modules' }}

    permissions:
      pull-requests: write
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # 5.4.0
        with:
          go-version: '1.24'
          check-latest: true

      - name: Tidy Go modules
        run: |
          go mod tidy

      - name: Check if any changes
        id: check
        run: |
          # Get list of changed files
          CHANGES=$(git diff --name-only)

          if [ -z "$CHANGES" ]; then
            echo "No changes detected, don't push"
            echo "push=no" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected, push needed"
            echo "push=yes" >> "$GITHUB_OUTPUT"
          fi

      - uses: chainguard-dev/actions/setup-gitsign@dd4524afd480a43ead9543a08be1c5004ee8b0a7 # v1.0.7
        if: ${{ steps.check.outputs.push == 'yes' }}

      - name: Amend Dependabot PR
        if: ${{ steps.check.outputs.push == 'yes' }}
        env:
          PULL_REQUEST_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -sam "tidy go modules"
          git push origin HEAD:${PULL_REQUEST_HEAD_REF}
