name: Dependabot Pull Request

on:
  pull_request:

permissions: {}

jobs:
  dependabot-check:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      dependabot-package-ecosystem: ${{ steps.dependabot-metadata.outputs.package-ecosystem }}

    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'cpanato/testing-ci-providers'
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v2.3.0


  go-mod-tidy:
    runs-on: ubuntu-latest

    needs: dependabot-check

    if: ${{ needs.dependabot-check.outputs.dependabot-package-ecosystem == 'go_modules' }}

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # 5.4.0
        with:
          go-version: '1.24'
          check-latest: true

      - name: Tidy Go modules
        run: |
          go mod tidy
