name: Dependabot Pull Request

on:
  pull_request_target:
    branches:
      - 'main'

permissions: {}

jobs:
  dependabot-check:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    outputs:
      is-go-mod-pr: ${{ steps.check-go-mod-changes.outputs.is-go-mod-pr }}

    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'cpanato/testing-ci-providers'
    steps:

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check for go.mod changes
        id: check-go-mod-changes
        run: |
          # Get the files changed in this PR
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})

          # Check if any go.mod files are in the changed files
          if echo "$CHANGED_FILES" | grep -q 'go.mod$'; then
            echo "go.mod files found in changes"
            echo "is-go-mod-pr=true" >> $GITHUB_OUTPUT
          else
            echo "No go.mod files found in changes"
            echo "is-go-mod-pr=false" >> $GITHUB_OUTPUT
          fi

  go-mod-tidy:
    runs-on: ubuntu-latest

    needs: dependabot-check

    if: ${{ needs.dependabot-check.outputs.is-go-mod-pr == 'true' }}

    permissions:
      pull-requests: write
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # 5.5.0
        with:
          go-version: '1.24'
          check-latest: true

      - name: Tidy Go modules
        run: |
          go mod tidy

      - name: Check if any changes
        id: check
        run: |
          # Get list of changed files
          CHANGES=$(git diff --name-only)

          if [ -z "$CHANGES" ]; then
            echo "No changes detected, don't push"
            echo "push=no" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected, push needed"
            echo "push=yes" >> "$GITHUB_OUTPUT"
          fi

      - uses: chainguard-dev/actions/setup-gitsign@16e2fd6603a1c6a1fbc880fdbb922b2e8e2be3e7 # v1.4.3
        if: ${{ steps.check.outputs.push == 'yes' }}

      - name: Amend Dependabot PR
        if: ${{ steps.check.outputs.push == 'yes' }}
        env:
          PULL_REQUEST_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -sam "tidy go modules"
          git push origin HEAD:${PULL_REQUEST_HEAD_REF}
