name: Build

on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    # container:
    #   image: "golang:1.19-alpine"
    services:
      vault:
        image: hashicorp/vault:latest
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
        options: >-
          --health-cmd "VAULT_ADDR=http://127.0.0.1:8200 vault status"
          --health-interval 1s
          --health-timeout 5s
          --health-retries 5

    env:
      VAULT_TOKEN: "root"
      VAULT_ADDR: "http://vault:8200"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: sigstore/cosign
          path: cosign
      - uses: innovationnorway/setup-vault@v1
        with:
          version: '~1.4'

      - run: apk add bash jq curl sudo

      - uses: imjasonh/setup-crane@e82f1b9a8007d399333baba4d75915558e9fb6a4 # v0.2

      - name: enable vault transit
        run: vault secrets enable transit
      - name: Acceptance Tests
        run: |
          ./scripts/e2e-kms.sh
