name: Verify reusable

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]
    paths:
      - terraform/**

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          terraform:
            - 'terraform/**'

  terraform-plan-staging:
    uses: cpanato/testing-ci-providers/.github/workflows/reusable.yaml@main
    needs: check
    if: ${{ needs.check.outputs.terraform == 'true' }}
    permissions:
      contents: read
      pull-requests: write

    with:
      terraform_mode: 'plan'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
