name: test wolfi

on:
  workflow_dispatch:
  pull_request:


jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wolfi-dev/wolfictl:latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - shell: bash
        run: |
          # Required git config unrelated to gitsign
          git config --global user.email "test@example.com"
          git config --global user.name "test"

      - name: Release
        id: release
        run: wolfictl --help
