name: Release Grafana Fork

on:
  workflow_dispatch:

jobs:
  release:
    name: Checkout
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - shell: bash
        run: |
          # Required git config unrelated to gitsign
          git config --local user.email "test@example.com"
          git config --local user.name "test-test"

      - name: Release
        id: release
        uses: docker://ghcr.io/wolfi-dev/wolfictl:latest
        with:
          entrypoint: /bin/bash
          args: -c "git config --list > test.txt && ls -la && head test.txt"
